# Generated by Django 4.1.3 on 2022-12-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['name'], 'verbose_name': 'Котик', 'verbose_name_plural': 'Котики'},
        ),
        migrations.AddField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='f', max_length=1),
        ),
    ]
