# Generated by Django 4.1.3 on 2022-12-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_cat_options_cat_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='about_cat',
            field=models.TextField(max_length=1000, null=True, verbose_name='About this cat'),
        ),
    ]
